### ISSUE TITLE
Weapons

### ISSUE THREAD

**Issue by StarGrabberDee** [ricochhet/Erupe#12]
Any ideas as to why the Tonfas/ Magnet spike are not Showing up in the game?
![image](https://user-images.githubusercontent.com/97332029/148701718-eff37736-637b-4ebc-a30e-18303a1eaf00.png)

**Comment by ssudai** [comment]
As a prerequisite, the Tonfa, Slash Axe, and Magnetic Spike will not be unlocked until after you are promoted to G rank.
Have you been promoted to G rank yet?
By the way, magnetic spikes will not be unlocked until you complete a special quest.

**Comment by StarGrabberDee** [comment]
Ooh Okay. I'm trying to figure out how to progress on that thank you
