### ISSUE TITLE
does the client patcher script to fix high grade error still exsist?

### ISSUE THREAD

**Issue by Arasutaru** [ricochhet/Erupe#15]
mhfo.dll unpacked.
[{'type': 'error', 'description': "Error: unable to find module 'mhfo.dll'", 'stack': "Error: unable to find module 'mhfo.dll'\n    at value (frida/runtime/core.js:336)\n    at onEnter (/script1.js:79)", 'fileName': 'frida/runtime/core.js', 'lineNumber': 336, 'columnNumber': 1}] => None
to fix this error

**Comment by Stefan240** [comment]
As I was updating the documentation, I did try if the script can be modified to allow the use of High Grade Assets in the launcher. Sadly the proposed solution to just replace all occurrences of `mhfo.dll` with `mhfo-hd.dll` did not work for me at that time. Maybe I just did something wrong, I don't know yet. 

At the moment the error still is present. 

Likely there is some other stuff with the script that also needs changing. If anyone knows how get the HG-Assets running, please chime in.

**Comment by Ciehdy** [comment]
You need to run the script with administrator privileges

**Comment by Ciehdy** [comment]
You can try to modify all "mhfo.dll" to "mhfo-hd.dll" in no_gg_jp.py and enable "High Grade Edition" in config,that you can load in high grade.

However, in my experience, servers are more likely to crash in high grade?

**Comment by Stefan240** [comment]
> You can try to modify all "mhfo.dll" to "mhfo-hd.dll" in no_gg_jp.py and enable "High Grade Edition" in config,that you can load in high grade.
> 
> However, in my experience, servers are more likely to crash in high grade?

Maybe I did something wrong? It did not work for me all that (patching that is). If someone gets it work please let me know, so I can add that to the documentation as well ^^

**Comment by Ciehdy** [comment]
Sorry I don't know more

**Comment by Arasutaru** [comment]
i got it running
just do what ciehdy said to do
