### ISSUE TITLE
no_gg_jp.py either not patching or something else

### ISSUE THREAD

**Issue by leviornotlevi** [ricochhet/Erupe#18]
![image](https://user-images.githubusercontent.com/97703579/149424739-748a4292-0e59-41f3-9edf-94e7d36d60ef.png)

cmd goes immediately from one to the other which leads me to believe its just not able to do what it needs to do

![image](https://user-images.githubusercontent.com/97703579/149424824-34a40fa6-80c3-4d2f-9397-b8235db682ce.png)

this shows up afterwards

figure i fucked something up but ive looked through the client setup guide about 10 times at this point

**Comment by Arasutaru** [comment]
friend is getting same issue trying to connectt to my server so i would also like to know the fix and for spome reason cant start the game anymore

**Comment by K-Lemu** [comment]
That error occurs because the client can't access the server address correctly and is trying to access the capcom server.
Have you entered the IP address to be accessed in the hosts file?
If you want to connect a local environment, enter 127.0.0.1
If you want to connect to an external IP, enter the external IP and check the port forwarding settings.
Also, if you change the hosts, be sure to delete the IE cache before starting the client.

**Comment by leviornotlevi** [comment]
@K-Lemu yep, 127.0.0.1 + the sites on the hosts file, unless theres some specific way i had to reformat em, deleted IE caches too but ill at least try it again if tinkering with more things messed it up

**Comment by leviornotlevi** [comment]
ye can confirm IE caches werent the problem, ill go over hosts stuff over some more just in case i can figure something out, appreciate the info that thats the problem

**Comment by Arasutaru** [comment]
carefull when changing the settings for some reason
![Screenshot 2022-01-13 193329](https://user-images.githubusercontent.com/97634224/149443267-01b8dc2e-82ea-4337-9baa-b296e4ccde2b.png)
i get this error now when i try to load the game

**Comment by leviornotlevi** [comment]
alright, fixed stuff in config, however

![image](https://user-images.githubusercontent.com/97703579/149444319-fa599883-98c3-43e3-b6a6-279e0180f991.png)

new problem just dropped

**Comment by Arasutaru** [comment]
you turned on high grade edition without the no_gg_jp set for the hg ver

**Comment by leviornotlevi** [comment]
i noticed that as soon as i posted the screenshot, though unsure where i turn that off, looking rn

**Comment by Arasutaru** [comment]
config first page

**Comment by Arasutaru** [comment]
also leviorno wanna play together? im trying to figure outhow to set it up for multiplayer but my friend knocked out and now i cant test it lol

**Comment by leviornotlevi** [comment]
im prolly just goin to bed after gettin this working

**Comment by Arasutaru** [comment]
lol damnit i need to get this working
