### ISSUE TITLE
Keep getting HTTP 404 when running no_gg_jp.py

### ISSUE THREAD

**Issue by JerCoolDude** [ricochhet/Erupe#29]
whenever I try to start the game it gives me the HTTP 404 page. I added the right things to the hosts file and made sure there were no #'s before the entries. The server seems to start just fine and when I try to start the game the server cmd says:
`127.0.0.1 - - [22/Jan/2022:02:20:56 +0800] "GET /serverlist.xml HTTP/1.0" 200 113`
Can anyone help me fix this?

Edit: I tried adding `127.0.0.1	www.mhf-z.jp` to the hosts file and after starting the game I got a different screen that said "Can't reach this page" and "make sure the web address https://www.mhf-z.jp is correct". Idk if this is progress or not.

**Comment by Stefan240** [comment]
- Did you follow the guide as posted? 
- Is your server running correctly? (a log might be helpful after you got the 404, a full one at that) Be sure to leave the Powershell (or cmd) window open after hitting `go run .`
- Does Client patching work as inteded? No weird errors while running the python script? ( a log might proof useful here as well)
- What does your host-file look like?
- Did you any MHF-Server running before if yes try cleaning out your Internet Explorer-Cache as stated here: https://github.com/ricochhet/Erupe/blob/master/docs/Troubleshooting.md#general-tips

Let me know if you still face difficulty

**Comment by JerCoolDude** [comment]
Its fixed now. All I had to do was delete my Internet Explorer cache
