### ISSUE TITLE
cant download client patcher from the link in the guide

### ISSUE THREAD

**Issue by soulmizute** [ricochhet/Erupe#34]
its litterally all i need to do to get the game to run but both links take me to a error 404 page and says this is not the page your looking for, ive resetted the page and have no idea what to do. can someone send me a link so i can get it.
thanks

**Comment by Stefan240** [comment]
Seems like I messed up while updating. I am sorry. Here is the file you look for: https://github.com/ricochhet/Erupe/blob/master/archive/no_gg_jp.py

@ricochhet Would you mind fixing the links for me? I don't have the time to do it at the moment.

**Comment by soulmizute** [comment]
hi stefan, thankyou this is really helpful, im happy i can now experience frontier. again thankyou

**Comment by Stefan240** [comment]
Link also seems fixed now. So this issue is resolved now. You may close it

**Comment by soulmizute** [comment]
ok cool
