### ISSUE TITLE
Error at Capcom Online Games logo

### ISSUE THREAD

**Issue by bimash** [ricochhet/Erupe#4]
I was able to manage to setup the server but when I tried to run the python launcher, this happen
it gives me error messages exactly at Capcom Online Games logo, probably in Japan locale because I did not install the language yet

![GFHWdb0Gzw](https://user-images.githubusercontent.com/13900655/148502821-9139ceab-ea19-4996-ba15-983393f94a37.png)
![rtAx3MXUyX](https://user-images.githubusercontent.com/13900655/148502848-4fe33be3-4fda-4c02-bfc5-19a7b5a39509.png)

**Comment by ssudai** [comment]
After you log in to the launcher, open the settings page and see if the Enable HighGradeEdition checkbox is checked.
If it is, uncheck it and try to launch again.

**Comment by bimash** [comment]
nvm just changed my locale and reinstall, everything fixed

now I can't get into a quest, stuck at now loading

**Comment by Ciehdy** [comment]
> 

You need to download the task file and put it in "Erupe\bin\quests"

**Comment by soulmizute** [comment]
if i may ask i got the same issue as this what did you reinstall
