### ISSUE TITLE
Frida unable to spawn executable

### ISSUE THREAD

**Issue by Molorius** [ricochhet/Erupe#49]
This is on a Windows 11 x64 machine. I installed python 3.8.10 x64 and frida 56.0.0. I got through the tutorial to the point in the client setup where you need to patch the executable, but cannot seem to launch it with frida. I run in command prompt:
```
py no_gg_jp.py
```

But get the error:

```python3
c:\Users\me\Downloads\mhf\MHF-ZZ_Installed_Files>py no_gg_jp.py
Traceback (most recent call last):
  File "no_gg_jp.py", line 135, in <module>
    main()
  File "no_gg_jp.py", line 18, in main
    pID = frida.spawn(executable_name)
  File "C:\Users\me\AppData\Local\Programs\Python\Python38\lib\site-packages\frida\__init__.py", line 57, in spawn
    return get_local_device().spawn(*args, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python38\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python38\lib\site-packages\frida\core.py", line 149, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.NotSupportedError: unable to spawn executable at 'mhf.exe': 0x000002e4
```

I can run the unpatched executable just fine from both command prompt and the file explorer. I also can successfully spawn frita processes of both 64 and 32 bit executables by running the following python commands in the respective folders:
```python3
import frida
frida.spawn("notepad.exe")
```
I have also tried with the 32 bit version of python 3.8. Do you have any other ideas I can try?

**Comment by Molorius** [comment]
I tried the same thing using Wine on Linux on the same machine. The script runs and I can see the initial sign in page, but it is unable to get past that point. I understand that Linux is not supported, just want to point out that frida does work on this machine. 

I also tried to run it on Windows 10 on a different computer. Same error with frida. Both are laptops with Intel cpus and integrated gpu, different cpu generations though.

**Comment by Stefan240** [comment]
My guess would be you did not run frida in an Administrator-Shell on the windows-maschine. 

Also I would love to get the client running on linux, but I just did not have the time to tinker around with it. It may work better with a patched exe but nothing I can say right now.

**Comment by Molorius** [comment]
Yes, I just needed to run as admin. Thank you for the suggestion. 

I am still running into problems logging in on Windows and Linux but that is an unrelated problem. I will send in a pull request if I get this working on Linux.

**Comment by Stefan240** [comment]
> Yes, I just needed to run as admin. Thank you for the suggestion.
> 
> I am still running into problems logging in on Windows and Linux but that is an unrelated problem. I will send in a pull request if I get this working on Linux.

If I can be of any assistance for getting it running on linux let me know

**Comment by Molorius** [comment]
I will make a new issue if so. My initial thought is that the "window.external." functions are not getting run, but I have not worked much with wine in the past.
