### ISSUE TITLE
unknown error windows after setting up erupe launcher

### ISSUE THREAD

**Issue by Gan1s** [ricochhet/Erupe#5]
o/ 
sorry for any typos, im not a native speaker

by setting up erupe's server and launcher, two error panels appear after selecting the default character
![unknown](https://user-images.githubusercontent.com/97305018/148577983-deb54b2f-fe36-45fc-9380-28e08c18b778.png)
i haven't installed any of the frontier documents in C: disk, so it may be some host problem, even that i put the locals on system32
![Sem título](https://user-images.githubusercontent.com/97305018/148578882-ab81add8-c0f2-40da-8152-0b618b25fc02.jpg)
alll the informations in the launcher configuration appear as a "???????" thing, just the 'high grade edition'  and 'internet explorer' are there, and changing any of these, the first error window and also this appears
![Sem título](https://user-images.githubusercontent.com/97305018/148580066-b1bce265-df2c-44f5-ba23-9568ee632160.jpg)
none of the powershell windows seems to identify the error, as the server is just saying 'password match!' and the launcher 'patch complete'

**Comment by Stefan240** [comment]
Are you using a taiwanese version of Monster Hunter Frontier?

**Comment by Gan1s** [comment]
so i've downloaded mhfz from the taiwan site a while ago, but already uninstalled all the archives, now the folder is fully from mhfzzinstalledfiles. The directory on the message doesn't even exist

**Comment by Stefan240** [comment]
did you ever start that taiwanese version?

**Comment by Gan1s** [comment]
i opened then appeared that gameguard errors, so i didn't anything else

**Comment by Stefan240** [comment]
since you had the taiwanese open once it could not hurt to clear Internet Explorers Cache and try again. This fixes a lot of weird behaviour in the launcher so is worth a shoot: 

>You may try this since sometimes the launcher can act funny:
> 
> Sometimes the Monster Hunter Frontier Client can act funky when testing things and reinstalling or changing the server you play on. As a first step when troubleshooting things in the MHF-Client it can help to delete _Internet Explorers_ (not Edge) Cache. This is pretty easy.
> 
>     * Open up Internet Explorer
> 
>     * Click on the little cogwheel on the top right
> 
>     * Select Safety -> Delete browsing history
> 
>     * In the now opening window check all the boxes and hit "Delete".
> 
> 
> After that restart the launcher

**Comment by Gan1s** [comment]
yeah, the same errors stay there

**Comment by Stefan240** [comment]
sad that you can't run the patched launcher in combination with Locale Emulator so one could atleast make sense of the gibberish in the warnings and text boxes.

**Comment by Gan1s** [comment]
ye i really don't know what to do

**Comment by Gan1s** [comment]
So, i've managed to resolve the first window issue, and maybe consequently the second too. I simply created a path file equal to the taiwan window and placed all the mhfzzinstalledfiles files there.
It seems that sometimes you are forced to place the files where the launcher wants to get them working correctly, it would be nice if you put this information in your new guide version.
Now im getting the same issue as the closed #4, but i didn't get how the guy managed to fix this, since the 'mhfo.dll' file are there in the game folder and the prompt can't find'em

**Comment by Ciehdy** [comment]
> So, i've managed to resolve the first window issue, and maybe consequently the second too. I simply created a path file equal to the taiwan window and placed all the mhfzzinstalledfiles files there. It seems that sometimes you are forced to place the files where the launcher wants to get them working correctly, it would be nice if you put this information in your new guide version. Now im getting the same issue as the closed #4, but i didn't get how the guy managed to fix this, since the 'mhfo.dll' file are there in the game folder and the prompt can't find'em

You can try to modify all "mhfo.dll" to "mhfo-hd.dll" in no_gg_jp.py and enable "High Grade Edition" in config

![image](https://user-images.githubusercontent.com/87915645/148646811-576a43d3-cf5e-4a7e-97db-995171dde423.png)

**Comment by Gan1s** [comment]
i could open the game normally by deselecting this option. To keep this high grade, do i have to rename mhfo on the folder or type something on cmd?

**Comment by Ciehdy** [comment]
> 

 modify all "mhfo.dll" to "mhfo-hd.dll" in no_gg_jp.py,that you can start game in hign grade

**Comment by Gan1s** [comment]
oh i did't get that i have to open the archive in the IDLE to make the changes. So, with all this set up, the game is now running correctly, thanks for all the support!
