### ISSUE TITLE
Not able to Connect? 

### ISSUE THREAD

**Issue by StarGrabberDee** [ricochhet/Erupe#8]
Constantly getting a Http 404 screen 

![image](https://user-images.githubusercontent.com/97332029/148635518-36891d9f-08d3-43fb-85b9-a1f43dfa98a8.png)
 
Just want to know exactly where did i go wrong at with this?

**Comment by Stefan240** [comment]
You may want to check the resolved issue #3 There some solutions you can try

**Comment by StarGrabberDee** [comment]
I tried some of the trouble shoots there and it seems i cannot connect to my server is there config.json i can see to see if i inputted the IPV in the right areas?

**Comment by Stefan240** [comment]
You can always try just using the localhost-IP-Adress, which is 127.0.0.1 for testing stuff. The only real thing you might need to change is the database-section in the config.json and make sure that your hosts file is configured correctly as seen in this step: https://github.com/ricochhet/Erupe#step-4-edit-your-hosts-file 

Try testing on localhost first and see if it works

**Comment by StarGrabberDee** [comment]
Alright i got it to work and then went to change my Locale to get the launcher to work now getting hit with 
![image](https://user-images.githubusercontent.com/97332029/148637693-97902486-e04a-45ca-990d-4f64f442f718.png)

**Comment by Stefan240** [comment]
You can copy the info of the textbox by clicking on it, then CRTL+C it and paste it into notepad. Then you may translate the text, maybe this can help us out later. Although I think something seems missing for whatever reason

**Comment by StarGrabberDee** [comment]
It says, " Failed to Write the INI file. [C:\Games\Capcom\Frontier\mhf.ini]

**Comment by StarGrabberDee** [comment]
I got it to work. Now i have to get into the game

**Comment by Stefan240** [comment]
Don't forget to disable High Grade Assets ^^

**Comment by StarGrabberDee** [comment]
Everything is working correctly ! Thanks for the help Although is there anyway to have all the Weapons and a working Dream room? Thats the only thing I dont have access to
