### ISSUE TITLE
shows full staff

### ISSUE THREAD

**Issue by Ciehdy** [ricochhet/Erupe#9]
My server can enter the room with a local client, but my friend enters the room and shows full staff
![1](https://user-images.githubusercontent.com/87915645/148638763-bc14cc32-ecb9-4350-8947-25098a889b7c.jpg)

**Comment by ricochhet** [comment]
Admittedly I don't have any experience with using the server for multiple people, just solo. Try making sure your port forwarding setup is correct? Otherwise I don't know, sorry.

**Comment by Arasutaru** [comment]
i get that i gotta port forward but how does the multiplayer even work like do i just run a server and have them change the config in the erupe master file and just have them run the game?

**Comment by Ciehdy** [comment]
I have solved this problem,only need to change the entries' IP in config.conf to a public IP
